services:
  autoretrieve:
    build: .
    environment:
      FULLNODE_API_INFO: ${FULLNODE_API_INFO:-wss://api.chain.love}
      AUTORETRIEVE_PER_MINER_RETRIEVAL_LIMIT: $AUTORETRIEVE_PER_MINER_RETRIEVAL_LIMIT
      AUTORETRIEVE_ENDPOINT: $AUTORETRIEVE_ENDPOINT
      AUTORETRIEVE_ENDPOINT_TYPE: $AUTORETRIEVE_ENDPOINT_TYPE
      AUTORETRIEVE_MAX_SEND_WORKERS: $AUTORETRIEVE_MAX_SEND_WORKERS
      AUTORETRIEVE_DISABLE_RETRIEVAL: $AUTORETRIEVE_DISABLE_RETRIEVAL
      AUTORETRIEVE_USE_FULLRT: $AUTORETRIEVE_USE_FULLRT
      AUTORETRIEVE_LOG_RESOURCE_MANAGER: $AUTORETRIEVE_USE_RESOURCE_MANAGER
      AUTORETRIEVE_LOG_RETRIEVALS: $AUTORETRIEVE_LOG_RETRIEVALS
    ports: 
      - "6746:6746"
    volumes:
      - ${AUTORETRIEVE_DATA_DIR:-./data}:/app/data
  # db:
  #   image: postgres