apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoretrieve
  namespace: autoretrieve
spec:
  template:
    spec:
      containers:
        - name: autoretrieve
          volumeMounts:
            - name: cache
              mountPath: /data
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: autoretrieve-cache-0
