apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: autoretrieve
  labels:
    app: autoretrieve
spec:
  selector:
    matchLabels:
      app: autoretrieve
  namespaceSelector:
    matchNames:
      - autoretrieve
  podMetricsEndpoints:
    - path: /metrics
      port: admin
