apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: autoretrieve
  name: autoretrieve-cache-0
  namespace: autoretrieve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: gp2
