apiVersion: v1
kind: Service
metadata:
  name: autoretrieve-libp2p
  namespace: autoretrieve
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    external-dns.alpha.kubernetes.io/hostname: autoretrieve.dev.cid.contact
