apiVersion: v1
kind: Service
metadata:
  name: autoretrieve-libp2p
  namespace: autoretrieve
  labels:
    app: autoretrieve
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    external-dns.alpha.kubernetes.io/hostname: autoretrieve.dev.cid.contact
spec:
  ports:
    - name: libp2p
      port: 6746
      targetPort: libp2p
  selector:
    app: autoretrieve
  type: LoadBalancer
