runs:
  using: "composite"
  steps:
    - name: Prepare for FFI build (macOS)
      if: matrix.os == 'macos'
      shell: bash
      run: |
        cargo install cargo-lipo
        brew install hwloc
    - name: Prepare for FFI build (Linux)
      if: matrix.os == 'ubuntu'
      shell: bash
      run: |
        sudo apt-get install ocl-icd-opencl-dev libhwloc-dev -y
    - name: Install & Build FFI
      shell: bash
      run: make all
